hostname Router-Core-Principal
ntp server pool.ntp.org
!
enable secret 9 $9$vD8sK78aJKd...
!
ip ssh version 2
!
interface GigabitEthernet0/1
 ip address 10.0.0.1 255.255.255.0
 no shutdown
!
ip http security-service
!
banner motd UNAUTHORIZED_ACCESS_IS_PROHIBITED_AND_MONITORED
!
logging host 192.168.1.50
!
line vty 0 4
 exec-timeout 5 0
 login local
 access-class 10 in
 transport input ssh
!




#What's wrong here?

#It has an SSH version 1 IP address (Outdated cryptography 🔴).

#The `exec-timeout` command is missing in line vty 0 4 (Unattended session exposed 🟡).

#The `motd` banner reveals the router model and the exact IOS version (7200_v12.4) (Information leak 🟡).

#There are no lines starting with `logging host` (It's not sending logs to the SIEM; the SOC is blind 🟡).

#enable secret vs enable password.